### PR TITLE
Gardens CRUD views continued.

### PR DESCRIPTION
**Pull request by AsiaCiesla**
Hi team, I updated the gardens' views. I made sure that everything works; fixed the broken Delete link and changed the show view, I hope you like it :)

image

### CODE REVIEW

**Comment by AsiaCiesla** [comment]
Oh! Just to add, I imagine a little map appearing in the white box :)

**Comment by AsiaCiesla** [comment]
For "bookings" link_to, I temporarily used a gardens_path instead of new_garden_booking_path, as the latter was displaying an error.

**Comment by lydia-scadding** [comment]
Asia this looks amazing!!!

**Comment by dantup01** [comment]
Wow Asia, looks amazing!

**Comment by AsiaCiesla** [comment]
Thank you both!

**Pull request merged**
